#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-XMLPost
version:      1.4
version_from: XMLPost.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
